Rails/proyectos/highschool/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'statics#static_pages'

  #Admin
  namespace :administrador do
    resources :users
    resources :courses
  end

  #Alumnos
  resources :alumns


end

Rails/proyectos/highschool/app/models/alumn.rb
class Alumn < ApplicationRecord
  belongs_to :course
end

Rails/proyectos/highschool/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rails/proyectos/highschool/app/models/course.rb
class Course < ApplicationRecord
  has_many :alumns
end

Rails/proyectos/highschool/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Rails/proyectos/highschool/app/controllers/administrador/courses_controller.rb
class Administrador::CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  #CRUD
  def new
    @course = Course.new
      #@alumn_course = Alumn.new
  end

  #Crear
  def create
    @course = Course.new(course_params)
    @alumn_course = @course.alumns

    if @course.save
      flash[:notice] = "Registro Exitoso!" #Notice debe ir siempre, es un mensaje
      redirect_to administrador_courses_path
    else
      render 'new'
    end

  end

  #Mostrar
  def show
    @course = Course.find(params[:id])
    @alumn_course = @course.alumns #Para cargar los alumnos de este curso

    #Voy a hacer mi CRUD de alumnos dentro del curso
    @alumn = Alumn.new
  end

  #Editar
  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      flash[:notice] = "Modificado con exito!"
      redirect_to administrador_courses_path(@course)
    else
      render 'edit'
    end
  end

  #Borrar
  def destroy
    @course = Course.find(params[:id]) #solo los detalles del producto (id)
    @course.destroy
    redirect_to administrador_courses_path
  end

  private
  def course_params
    params.require(:course).permit(:name, :finicio, :ffinal)
  end

  def validar_admin
    unless current_user.administrador
      redirect_to root_path
    end
  end

end

Rails/proyectos/highschool/app/controllers/administrador/users_controller.rb
class Administrador::UsersController < ApplicationController

  #Antes de ejecutarse cualquiera de los métodos:
  before_action :validar_admin

  def index
    @users = User.all
  end

  #CRUD
  def new
    @user = User.new
  end

  #Crear
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Registro Exitoso!" #Notice debe ir siempre, es un mensaje
      redirect_to administrador_users_path
    else
      render 'new'
    end

  end

  #Mostrar
  def show
    @user = User.find(params[:id])
  end

  #Editar
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Modificado con exito!"
      redirect_to administrador_users_path(@user)
    else
      render 'edit'
    end
  end

  #Borrar
  def destroy
    @user = User.find(params[:id]) #solo los detalles del producto (id)
    @user.destroy
    redirect_to administrador_users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :administrador)
  end

  def validar_admin
    unless current_user.administrador
      redirect_to root_path
    end
  end

end

Rails/proyectos/highschool/app/controllers/alumns_controller.rb
class AlumnsController < ApplicationController

  def index
    @alumns = Alumn.all
  end

  #CRUD
  def new
    @alumn = Alumn.new
  end

  #Crear
  def create
    @alumn = Alumn.new(alumn_params)
    #@alumn.course = Course.find_by(params[:id])

    if @alumn.save
      flash[:notice] = "Registro Exitoso!" #Notice debe ir siempre, es un mensaje
      redirect_to root_path
    else
      render 'administrador/courses/show'
    end

  end

  #Mostrar
  def show
    @alumn = Alumn.find(params[:id])
  end

  #Editar
  def edit
    @alumn = Alumn.find(params[:id])
  end

  def update
    @alumn = Alumn.find(params[:id])
    if @alumn.update(alumn_params)
      flash[:notice] = "Modificado con exito!"
      redirect_to alumns_path(@alumn)
    else
      render 'edit'
    end
  end

  #Borrar
  def destroy
    @alumn = Alumn.find(params[:id]) #solo los detalles del producto (id)
    @alumn.destroy
    redirect_to alumns_path
  end

  private
  def alumn_params
    params.require(:alumn).permit(:name, :age, :phone, :email, :course_id)
  end


end

Rails/proyectos/highschool/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception



end

Rails/proyectos/highschool/app/controllers/statics_controller.rb
class StaticsController < ApplicationController

  #No le puse def index ¿Por qué?
  # index, lo uso cuando quiero mostrar todos los registros de una tabla
  # no es correcto ponerle index... sino static_pages porque este no tiene que ver con las rutas, ni los verbos
  # Este StacitControoler, es un controlador sin verbos, aqui nunca vas a encontrar un show, destroy, create...
  # sino que aqui vamos a crear acciones que no están relacionadas con esos verbos
  def static_pages

  end

end

Rails/proyectos/highschool/app/helpers/administrador/courses_helper.rb
module Administrador::CoursesHelper
end

Rails/proyectos/highschool/app/helpers/administrador/users_helper.rb
module Administrador::UsersHelper
end

Rails/proyectos/highschool/app/helpers/alumns_helper.rb
module AlumnsHelper
end

Rails/proyectos/highschool/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/proyectos/highschool/app/helpers/statics_helper.rb
module StaticsHelper
end

Rails/proyectos/highschool/app/views/administrador/users/edit.html.erb
<div class="row justify-content-md-center" >
  <h3>Editar un usuario</h3>

  <% if @user.errors.any? %>
    <h4>Hubo errores con el registro, revisa que...</h4>
    <ul>
      <% @user.errors.full_messages.each do |errores| %>
        <li><%= errores %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<br>
<br>

<div class="row justify-content-md-center" >
  <%= form_with model: [:administrador, @user], local: true do |campo| %>

    <div class="row justify-content-start">
      <div class="col col-lg-6">
        <%= campo.label :Email %>
      </div>
      <div class="col col-lg-2">
        <%= campo.text_field :email %>
      </div>
    </div>

    <div class="row justify-content-start">
      <div class="col col-lg-6">
        <%= campo.label :Contraseña %>
      </div>
      <div class="col col-lg-2">
        <%= campo.password_field :password %>
      </div>
    </div>

    <div class="row justify-content-start">
      <div class="col col-lg-6">
        <%= campo.label :Repetir_Contraseña %>
      </div>
      <div class="col col-lg-2">
        <%= campo.password_field :password_confirmation %>
      </div>
    </div>

    <div class="row justify-content-start">
      <div class="col col-lg-6">
        <%= campo.label :Administrador %>
      </div>
      <div class="col col-lg-2">
        <%# elemento.select(:status_type, options_for_select(['Administrador', true], ['Doctor', false])) %>
        <%= campo.check_box :administrador %>
      </div>

    </div>

    <br>
    <div class="row justify-content-end">
      <div class="col col-lg-8">
        <%= campo.submit "Guardar", class: "btn btn-success"  %>
        <%= link_to "Cancelar", administrador_users_path, class: "btn btn-warning" %>
      </div>
    </div>

  <% end %>

</div>

Rails/proyectos/highschool/app/views/administrador/users/index.html.erb
<div class="row justify-content-md-center">
  <h1>Gestión de Usuarios </h1>
</div>

<br>
<br>
<div class="row justify-content-md-center">
    <%= link_to "Registrar un nuevo Usuario", new_administrador_user_path, class: "btn btn-dark"  %>
    <%= link_to "Estadísticas", '#{admin_stadistic_path}', class: "btn btn-warning"  %>
</div>

<br>
<br>

<div class="row justify-content-md-center">
  <div class="col-6">
    <h5>Lista de Usuarios</h5>
    <table class="table table-striped">
      <thead class="thead-dark">
      <tr>
        <th>Email</th>
        <th>Fecha Ingreso</th>
        <th>Administrador</th>
        <th colspan="3">Accion</th>
      </tr>
      </thead>

      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.created_at %></td>
          <td><%= user.administrador %></td>
          <td>
            <%= link_to "Detalle", administrador_user_path(user.id) %>
            <%= link_to "Editar", edit_administrador_user_path(user) %>
            <%= link_to "Borrar", administrador_user_path(user), method: :delete, data: { confirm: "Estas seguro?"}  %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row justify-content-md-center">
    <h6><%= link_to "Volver", root_path, class: "btn btn-primary"  %></h6>
</div>

Rails/proyectos/highschool/app/views/administrador/users/new.html.erb
<div class="row justify-content-md-center" >
<h3>Registro de usuario</h3>

<% if @user.errors.any? %>
  <h4>Hubo errores con el registro, revisa que...</h4>
  <ul>
    <% @user.errors.full_messages.each do |errores| %>
      <li><%= errores %></li>
    <% end %>
  </ul>
<% end %>
</div>

<br>
<br>

<div class="row justify-content-md-center" >
<%= form_with model: [:administrador, @user], local: true do |campo| %>

  <div class="row justify-content-start">
    <div class="col col-lg-6">
      <%= campo.label :Email %>
    </div>
    <div class="col col-lg-2">
      <%= campo.text_field :email %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col col-lg-6">
      <%= campo.label :Contraseña %>
    </div>
    <div class="col col-lg-2">
      <%= campo.password_field :password %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col col-lg-6">
      <%= campo.label :Repetir_Contraseña %>
    </div>
    <div class="col col-lg-2">
      <%= campo.password_field :password_confirmation %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col col-lg-6">
      <%= campo.label :Administrador %>
    </div>
    <div class="col col-lg-2">
      <%# elemento.select(:status_type, options_for_select(['Administrador', true], ['Doctor', false])) %>
      <%= campo.check_box :administrador %>
    </div>

  </div>

  <br>
    <div class="row justify-content-end">
      <div class="col col-lg-8">
        <%= campo.submit "Guardar", class: "btn btn-success"  %>
        <%= link_to "Cancelar", administrador_users_path, class: "btn btn-warning" %>
      </div>
    </div>

<% end %>

</div>

Rails/proyectos/highschool/app/views/administrador/users/show.html.erb
<div class="row justify-content-md-center">
<h1>Detalle del Usuario </h1>
</div>

<br>
<br>

<div class="row justify-content-md-center" >
<%= form_with model: [:administrador, @user], local: true do |entity| %>

  <div class="row justify-content-start">
    <div class="col col-lg-6">
      <%= entity.label :Email %>
    </div>
    <div class="col col-lg-2">
      <%= entity.text_field :email, :disabled => true  %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col col-lg-6">
      <%= entity.label :FechaIngreso %>
    </div>
    <div class="col col-lg-2">
      <%= entity.text_field :created_at, :disabled => true  %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col col-lg-6">
      <%= entity.label :FechaRegistro %>
    </div>
    <div class="col col-lg-2">
      <%= entity.text_field :updated_at, :disabled => true  %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col col-lg-6">
      <%= entity.label :Administrador %>
    </div>
    <div class="col col-lg-2">
      <%# elemento.select(:status_type, options_for_select(['Administrador', true], ['Doctor', false])) %>
      <%= entity.check_box :administrador, :disabled => true %>
    </div>

  </div>

  <br>

  <div class="row justify-content-end">
    <div class="col col-lg-12">
      <%= link_to "Editar", edit_administrador_user_path, class: "btn btn-primary"  %>
      <%= link_to "Borrar", administrador_user_path, method: :delete, data: { confirm: "Estas seguro?"} , class: "btn btn-danger"  %>
      <%= link_to "Cancelar", administrador_users_path, class: "btn btn-warning" %>
    </div>
  </div>



<% end %>

</div>

Rails/proyectos/highschool/app/views/alumns/edit.html.erb
<div class="row justify-content-md-center" >
  <h3>Modificar  Alumno</h3>

  <% if @alumn.errors.any? %>
    <h4>Hubo errores con el registro, revisa que...</h4>
    <ul>
      <% @alumn.errors.full_messages.each do |errores| %>
        <li><%= errores %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<br>
<br>

<div class="row justify-content-md-center" >
  <%= form_for(@alumn, html: {class: "col-s12"}) do |entity| %>

    <div class="row justify-content-start">
      <div class="col col-lg-6">
        <%= entity.label :Nombre %>
      </div>
      <div class="col col-lg-2">
        <%= entity.text_field :name %>
      </div>
    </div>

    <div class="row justify-content-start">
      <div class="col col-lg-6">
        <%= entity.label :Edad %>
      </div>
      <div class="col col-lg-2">
        <%= entity.text_field :age %>
      </div>
    </div>

    <div class="row justify-content-start">
      <div class="col col-lg-6">
        <%= entity.label :Telefono %>
      </div>
      <div class="col col-lg-2">
        <%= entity.text_field :phone %>
      </div>
    </div>

    <div class="row justify-content-start">
      <div class="col col-lg-6">
        <%= entity.label :Mail %>
      </div>
      <div class="col col-lg-2">
        <%= entity.text_field :email %>
      </div>
    </div>


    <br>
    <div class="row justify-content-end">
      <div class="col col-lg-12">
        <%= entity.submit "Guardar", class: "btn btn-success"  %>
        <%= link_to "Cancelar", alumns_path, class: "btn btn-warning" %>
      </div>
    </div>

  <% end %>
</div>

Rails/proyectos/highschool/app/views/alumns/index.html.erb
<h1>Test</h1>

Rails/proyectos/highschool/app/views/alumns/show.html.erb
<div class="row justify-content-md-center" >
  <h3>Detalle Alumno</h3>

  <% if @alumn.errors.any? %>
    <h4>Hubo errores con el registro, revisa que...</h4>
    <ul>
      <% @alumn.errors.full_messages.each do |errores| %>
        <li><%= errores %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<br>
<br>

<div class="row justify-content-md-center" >
  <%= form_for(@alumn, html: {class: "col-s12"}) do |entity| %>

    <div class="row justify-content-start">
      <div class="col col-lg-6">
        <%= entity.hidden_field :Curso %>
      </div>
      <div class="col col-lg-2">
        <%= entity.hidden_field :course_id, value: @course.id, :disabled => true  %>
      </div>
    </div>

    <div class="row justify-content-start">
      <div class="col col-lg-6">
        <%= entity.label :Nombre %>
      </div>
      <div class="col col-lg-4">
        <%= entity.text_field :name, :disabled => true %>
      </div>
    </div>

    <div class="row justify-content-start">
      <div class="col col-lg-6">
        <%= entity.label :Edad %>
      </div>
      <div class="col col-lg-4">
        <%= entity.text_field :age, :disabled => true %>
      </div>
    </div>

    <div class="row justify-content-start">
      <div class="col col-lg-6">
        <%= entity.label :Telefono %>
      </div>
      <div class="col col-lg-4">
        <%= entity.text_field :phone, :disabled => true %>
      </div>
    </div>

    <div class="row justify-content-start">
      <div class="col col-lg-6">
        <%= entity.label :Mail %>
      </div>
      <div class="col col-lg-4">
        <%= entity.text_field :email, :disabled => true %>
      </div>
    </div>


    <br>
    <div class="row justify-content-end">
      <div class="col col-lg-12">
        <%= link_to "Editar", edit_alumn_path(entity), class: "btn btn-success" %>
        <%= link_to "Cancelar", alumns_path, class: "btn btn-warning" %>
      </div>
    </div>

  <% end %>
</div>

Rails/proyectos/highschool/app/views/shared/_menu.html.erb
<nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">

      <li class="nav-item active" >
        <%= link_to 'Home', root_path, class:'nav-link' %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Cursos', administrador_courses_path, class:'nav-link' %>
        </li>
        <% if current_user.administrador %>
          <li class="nav-item active">
            <%= link_to 'Usuarios', administrador_users_path, class:'nav-link' %>
          </li>
        <% end %>

      <% end %>

    </ul>

    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
        </li>
      <% else %>
        <!--
        <li class="nav-item">
          <%# link_to 'Registrarse', new_user_registration_path, class:'nav-link' %>
        </li>
        -->
        <li class="nav-item">
          <%= link_to 'Inciar Sesión',  new_user_session_path, class: "btn btn-primary" %>
        </li>
      <% end %>
    </ul>

  </div>
</nav>