Rails/proyectos/university/config/routes.rb
Rails.application.routes.draw do
  root 'courses#index' #ruta root es cursos de la universidad
  get 'about', to: 'pages#about'
  get 'courses/new', to: 'courses#new'

  resources :students, except: [:destroy]
  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'

end

Rails/proyectos/university/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rails/proyectos/university/app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: {minimum:5, maximum: 50}
  validates :short_name, presence: true, length: {minimum:3, maximum: 5}
  validates :description, presence: true, length: {minimum:10, maximum: 100}

  has_many :student_courses
  has_many :students, through: :student_courses

end

Rails/proyectos/university/app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {minimum:5, maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password
  has_many :student_courses
  has_many :courses, through: :student_courses
end

Rails/proyectos/university/app/models/student_course.rb
class StudentCourse < ApplicationRecord

  belongs_to :student
  belongs_to :course

end

Rails/proyectos/university/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :require_user

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:notice] = "Debes iniciar sesion primero"
      redirect_to login_path
    end
  end


end

Rails/proyectos/university/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_user

  def index
    @courses = Course.all
  end

  def new

  end

end

Rails/proyectos/university/app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  skip_before_action :require_user, only: [:new, :create]

  def new

  end

  def create
    student = Student.find_by(email: params[:logins][:email].downcase)
    if student && student.authenticate(params[:logins][:password_digest])
      session[:student_id] = student.id
      flash[:notice] = "Bienvenido! :)"
      redirect_to student

    else
      flash.now[:notice] = "Creedenciales no validas"
      render 'new'
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:notice] = "Vuelve pronto! :)"
    redirect_to root_path

  end


end

Rails/proyectos/university/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user
  def about

  end
end

Rails/proyectos/university/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  before_action :set_student, only: [:show, :edit, :update]
  before_action  :require_same_student, only: [:edit, :update]

  def index
    @students = Student.all

  end

  #Alta estudiante
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = "Registrado correctamente!"
      redirect_to @student

    else
      render 'new'

    end

  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :password_digest, :password_confirmation)
  end

  def require_same_student
    if current_user != @student
      flash[:notice] = "Puedes editar solo tu perfil"
      redirect_to student_path(current_user)
    end
  end

  #Consulta Estudiante
  def show
    #Borramos el patrón comun

  end

  #Editar Estudiante
  def edit
    #Borramos el patrón comun
  end

  def update
    #Borramos el patrón comun
    if @student.update(student_params)
      flash[:notice] = "Se ha modificado tu perfil"
      redirect_to students_path(@student)
    else
      render 'edit'
    end

  end

  private
  def set_student
    @student = Student.find(params[:id])
  end



end

Rails/proyectos/university/app/helpers/application_helper.rb
module ApplicationHelper

  def session_link
    if(logged_in?)
      link_to("logout", login_path, method: :delete)
    else
      link_to("login", login_path)
    end
  end
end

Rails/proyectos/university/app/views/courses/index.html.erb
<!--Creamos una carpeta y un index.html.erb que
describa nuestro controlador-->
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Lista de Cursos</h3>
  </div>
</div>

<h1>Cursos: </h1>


<div class="row">

  <!--Llenamos con datos desde la base-->
  <% @courses.each do |course| %>
  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= course.short_name %>: <%= course.name %> </span>
        <p><%= course.description %></p>
      </div>
      <div class="card-action">
        <a href="#">Inscribirse</a>
        <a href="#">Info</a>
      </div>
    </div>
  </div>
  <% end %>


</div>

Rails/proyectos/university/app/views/courses/new.html.erb
<h1>Alta Cursos</h1>

Rails/proyectos/university/app/views/logins/new.html.erb
<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header">Iniciar Sesion</h3>

        <!--Formulario-->
        <div class="row">
          <%= form_for(:logins, html: {class: "col s12"}) do |f| %>

            <!--Email-->
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :email, placeholder: "E-mail", autofocus:true %>
              </div>
            </div>

            <!--Password-->
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password_digest, placeholder: "Contraseña", autofocus:true %>
              </div>
            </div>

            <!--Boton-->
            <div class="row">
              <div class="input-field col s12">
                <%= f.button '<i class="material-icons right">arrow_forward</i>Iniciar Sesion'.html_safe, class: "btn orange waves-effect waves-light right" %>
              </div>
            </div>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

Rails/proyectos/university/app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">

        <!--Titulo-->
        <div class="row">
          <div class="col s12">
            <h3 class="center-align"><%= @student.new_record? ? "Registrar" : "Editar Perfil" %></h3>
          </div>
        </div>

        <!--Formulario-->
        <div class="row">
          <%= form_for(@student, html: {class: "col s12"}) do |f| %>

            <!--Nombre-->
            <div class="row">
              <div class="input-field col s12 ">
                <%= f.text_field :name, placeholder: "Nombre", autofocus:true %>
              </div>
            </div>

            <!--Email-->
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :email, placeholder: "E-mail", autofocus:true %>
              </div>
            </div>

            <!--Password-->
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password, placeholder: "Contraseña", autofocus:true %>
              </div>
            </div>

            <!--ConfirmacionPassword-->
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password_confirmation, placeholder: "Comprueba tu contraseña", autofocus:true %>
              </div>
            </div>


            <!--Boton-->
            <div class="row">
              <div class="input-field col s12">
                <%= f.button(@student.new_record? ? "Registrar" : "Editar", class: "btn orange waves-effect waves-light right")%>
              </div>
            </div>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

Rails/proyectos/university/app/views/students/edit.html.erb
<%= render 'students/form' %>

Rails/proyectos/university/app/views/students/index.html.erb
<!--Creamos una carpeta y un index.html.erb que
describa nuestro controlador-->
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Lista de Estudiantes</h3>
  </div>
</div>

<h1>Cursos: </h1>


<div class="row">

  <!--Llenamos con datos desde la base-->
  <% @students.each do |student| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Nombre: <%= student.name %></span>
          <p>Email: <%= student.email %></p>
          <p>Cursando: Ninguno</p>
        </div>
        <div class="card-action">
          <%= link_to "Ver perfil", student_path(student) %>>
        </div>
      </div>
    </div>
  <% end %>


</div>

Rails/proyectos/university/app/views/students/new.html.erb
<%= render 'students/form' %>

Rails/proyectos/university/app/views/students/show.html.erb
<div class="row sign-up-form">

  <!--Llenamos con datos desde la base-->
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Nombre: <%= @student.name %></span>
          <p>Email: <%= @student.email %></p>
          <p>Cursando: Ninguno</p>
        </div>
      </div>

      <!--Boton con estilo de editar e icono-->
      <% if current_user == @student %>
        <%= link_to '<i class="material-icons right">create</i>"Editar Perfil"'.html_safe, edit_student_path(@student), class: "waves-effect waves-light btn" %>
     <% end %>

    </div>
</div>